import "@/styles/globals.css";
import type { AppProps } from 'next/app';

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`} style={{ backgroundImage: 'url(/background_gradient.png)', backgroundSize: 'cover', backgroundPosition: 'center', minHeight: '100vh' }}>{children}</body>
    </html>
  );
}
